### ISSUE TITLE
Difference between ShouldReturn and WillBe returned by

### ISSUE THREAD

**Issue by pettercastro** [mockito/mockito-scala#101]
When stubbing I always use willBe, however now that I need to chain calls, I see that does not exist in the `willBe` but just in the `shouldReturn` option. I wonder what is the difference between both? Because `shouldReturn` sounds more like an assertion instead of a stubbing

**Comment by ultrasecreth** [comment]
The main difference is that `willBe` stubs the method before calling it, so it works better when using spies or strict mode.

I personally prefer the `shouldReturn` syntax, but I guess it's a matter of taste.

I'm not really sure that `shouldReturn` sounds like an assertion but since version 1.4.0 you can use `shouldReturn`, `mustReturn` and `returns` interchangeably, does any of those options sound better?
