### ISSUE TITLE
Getting `ClassCastException: scala.collection.immutable` when calling `willAnswer()`

### ISSUE THREAD

**Issue by evertones** [mockito/mockito-scala#159]
I've upgraded Mockito version in a Scala project from 1.10.19 to 3.0.0.
Initially I did it with the standard version of Mockito, but after some time struggling with the error I tried `mockito-scala` (version `1.5.18`).
After fixing all the compilation errors, imports and broken tests, I'm still stuck with a test that customises an `Answer` for a method that receives a function by parameter.

This is the method I want to test:
```
def findByGroupID(): AccountsResult = {
    val accounts = () => PageableCollection(pageable => accountService.findBy("MyRoleType", Set(true), pageable))
    val data = accountDataProcessor.process(accounts)

    new AccountsResult(data.asJava)
}
```

This is the mocks/stubs:
```
accountDataProcessor = mock[AccountDataProcessor]
accountService       = mock[AccountService]
controller           = new AccountController(accountDataProcessor, accountService)

given(accountService.findBy(any[String](), any[Set[Boolean]](), any[Pageable]()))
    .willReturn(new PageImpl(List.empty[Account].asJava))

given(accountService.findBy(any(), any(), any()))
    .willReturn(new PageImpl(List(new Account(...)).asJava), new PageImpl(List.empty[Account].asJava))

given(accountDataProcessor.process(any[() => Iterable[Account]]())).willAnswer { invocation =>
    invocation.getArgument(0).asInstanceOf[() => Iterable[Account]]
        .apply()
        .map(account => AccountData(account)).toList
}
```

When running the test I get the following exception in both standard Mockito and `scala-mockito`:
```
java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to org.evertones.dtos.AccountData
    at org.mockito.codegen.AccountDataProcessor$MockitoMock$1415670476.process(Unknown Source)
    at org.mockito.codegen.AccountDataProcessor$MockitoMock$1415670476.process(Unknown Source)
    at org.evertones.controller.AccountController.findByGroupID(AccountController.scala:18)
    at org.evertones.test.units.AccountSpec.$anonfun$new$6(AccountSpec.scala:70)
    at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    at org.scalatest.Transformer.apply(Transformer.scala:22)
    at org.scalatest.Transformer.apply(Transformer.scala:20)
    at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
    ...
```

I created a small repo that mimic the error in [my mockito-scala repo](https://github.com/evertones/mockito-scala).

Any help or guidance is appreciated.

**Comment by ultrasecreth** [comment]
I've taken a look at your repo and I have a couple of observations

Let's start with your error, the problem happens due to the JVM type erasure when using generics, your overloaded method `process` relies on `Function0[+R]` and the only difference between the 2 is a different type on `R`, that works in compile time, but on runtime that information is lost, and because you are using the `any()` matcher, Mockito will take the first method that matches, which could be either of those here. TL;DR; get rid of the overload ;)

On a different note, upgrading to `mockito-scala` per se does nothing to help you out with this kinda errors that sometimes are due to the interoperability between Scala and Java (not this case though). If you wanna take advantage of `mockito-scala` you should stop using the APIs provided by `mockito-core` and/or `scalatest`

So if you wanna keep using the old syntax please use `import org.mockito.{ArgumentMatchersSugar, MockitoSugar}`, note that the BDD syntax is not supported as `mockito-scala` introduces the idiomatic syntax for Scala which ideally should be what you use as it's where some of the advances features exists (`import org.mockito.{ArgumentMatchersSugar, IdiomaticMockito}`).
Check the README for more details or feel free to ping me on Gitter.

**Comment by evertones** [comment]
@bbonanno: Thank you very much for the quick and precise reply.
I'm closing this issue as it's a problem in the code, not a bug in `scala-mockito` or `mockito` itself.
