### ISSUE TITLE
Stubbing void methods

### ISSUE THREAD

**Issue by Krever** [mockito/mockito-scala#175]
Hey, I just hit the limitation of raw mockito, which doesnt allow stubbing void methods. Example:
```
trait Foo {
  def foo(): Unit
}

val foo = mock[Foo]
foo.foo() shouldReturn (())
```
Error:
```
'foo' is a *void method* and it *cannot* be stubbed with a *return value*!
Voids are usually stubbed with Throwables:
    doThrow(exception).when(mock).someVoidMethod();
If you need to set the void method to do nothing you can use:
    doNothing().when(mock).someVoidMethod();
For more information, check out the javadocs for Mockito.doNothing().
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. The method you are trying to stub is *overloaded*. Make sure you are calling the right overloaded version.
2. Somewhere in your test you are stubbing *final methods*. Sorry, Mockito does not verify/stub final methods.
3. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.
4. Mocking methods declared on non-public parent classes is not supported.
```

Coud mockito-scala intercept such scenario and make it work? `shouldAnswer` works fine, so probably its mechanism could be used with `_ => ()` to simulate raw stubbing.

Alternatively mockito-scala could expose some version of `doNothing` as I believe its not currently available.

**Comment by ultrasecreth** [comment]
Is this to use with spies? cause a mock would return `Unit` by default in that scenario without the need of stubbing it.

**Comment by Krever** [comment]
Hmm not at all. I just didnt know about the default and wanted to stub it as everything else. This is some sort of special case? I hoped that the strict verification of stubbings would complain if I stub such `void` method unnecessarily...

**Comment by ultrasecreth** [comment]
Is not really a special case, any method in a mock will do nothing by default and it will have to return something, if it's a primitive it will be it's default value, otherwise a `SmartNull` (unless it's a final class in which it will have to return `null`). For a `void` method the same principle applies and Scala will give you back the `Unit` instance as a `void` call happened.

I didn't try what happens with the strict mode, but if you actually call the method it won't complain about being stubbed and not used.

**Comment by Krever** [comment]
I see! Okey, now its clear that everything is coherent, yet from the user perspective is kind of surprising that `Unit`-returning method cannot be stubbed and the fact that it will work out of the box is also quite unexpected. 

The case here is that `void` or `Unit` being a primitive has this default mockito behaviour, yet at the same time `Unit` has exactly one value so it makes it quite bugprone, because you have no control over executing such implicitly stubbed methods. The best one can do is probably to manually verify the call at the end of test (checking if the method was called and with what arguments). Thats kind of problematic where everything else relies on the implicit verification of strict mode... 

Do you think there is anything mockito-scala can do in this case to improve what raw mockito provides?

**Comment by ultrasecreth** [comment]
The thing is that stubbing a `Unit` method only makes sense if you wanna make it throw an exception, otherwise the only thing you want out of it is to verify it was called as you mentioned. Stubbing it with a `Unit` value to leverage on the strict mode could be done, but it feels quite hacky, the point of strict mode is to avoid repeating yourself (verifying what you stubbed), not remove 100% of the verifications. 

This case I'd argue is a good example of when the right thing to do is to use a verification which would have a clear intention and purpose.

Using a not-really-necessary stubbing to verify implicitly hides that intention and may end up in someone removing that line in the future as it may think it is not required (there is nothing that tells you it's there for verification purposes).

**Comment by Krever** [comment]
For me the point of using strict mode is to ensure no calls go unnoticed. yet there is this small corner case that doesn't require stubbing and the whole reasoning is no longer valid. This breaks the whole mental model of tests for me...

**Comment by ultrasecreth** [comment]
But that would still be the case, if you don't verify the call it will fail right?
If it doesn't fail then that's a bug.

**Comment by ultrasecreth** [comment]
was thinking, maybe having an idiomatic version of `doNothing().when(mock).someVoidMethod();` would solve your problem?

**Comment by Krever** [comment]
I checked and you're right, strict mode still does work, which is good.
And yes, idiomatic version of `doNothing` is what I need. So in perfect world I would like to write

```
myMock.voidMethod().shouldDoNothing()
```

Although, I would probably prefer `.shouldReturnUnit` or `shouldReturn(())` just to have a uniform way of declaring verification via stubbing (even if return value is redundant in this case)
