### ISSUE TITLE
IdiomaticMockito cannot be used with ResetMocksAfterEachTest

### ISSUE THREAD

**Issue by stevebakh** [mockito/mockito-scala#217]
Hi!

This is almost the same as a previously raised (and fixed) issue: https://github.com/mockito/mockito-scala/issues/32

When mixing in both `IdiomaticMockito` with `ResetMocksAfterEachTest` into a test spec, I get the following error:

> Error:(21, 7) overriding method withFixture in trait MockitoSessionFixture of type (test: BillingSchedulerAgentLiveTest.this.NoArgTest)org.scalatest.Outcome;
 method withFixture in trait ResetMocksAfterEachTest of type (test: BillingSchedulerAgentLiveTest.this.NoArgTest)org.scalatest.Outcome has weaker access privileges; it should be public
class BillingSchedulerAgentLiveTest

```scala
"org.scalatest" %% "scalatest" % "3.1.1"
"org.mockito" %% "mockito-scala" % "1.13.4"
"org.mockito" %% "mockito-scala-scalatest" % "1.13.4"
```

**Comment by ultrasecreth** [comment]
Hi @stevebakh, would you mind posting a snippet of the code that generates that error, including the test you're trying to write?
This is so I can a)fix the right thing and b) add such test to our codebase so is not an issue ever again

Thanks!

**Comment by stevebakh** [comment]
Sorry! I should have provided that to begin with, my bad. 

```scala
import org.mockito.scalatest.{IdiomaticMockito, ResetMocksAfterEachTest}
import org.scalatest.flatspec.AnyFlatSpec

class IdiomaticMockitoTest 
    extends AnyFlatSpec 
    with IdiomaticMockito 
    with ResetMocksAfterEachTest {

  trait Foo {
    def bar(): Unit
  }

  it should "not fail to compile!" in {
    val fooMock = mock[Foo]
    fooMock.bar()
    fooMock.bar was called
  }
}
```

**Comment by ultrasecreth** [comment]
It seems to me that you're using the wrong imports, if you use `org.mockito.scalatest.IdiomaticMockito` then you are (by extension) using `org.mockito.scalatest.MockitoSessionFixture` which can't be used in conjuntion with `org.mockito.scalatest.ResetMocksAfterEachTest`, check [here](https://github.com/mockito/mockito-scala#orgmockitointegrationsscalatestresetmocksaftereachtest--orgmockitointegrationsscalatestresetmocksaftereachasynctest)

The solution is to use `org.mockito.IdiomaticMockito` which can be used with `org.mockito.scalatest.ResetMocksAfterEachTest`

That said, in the test example you posted you don't really need `org.mockito.scalatest.ResetMocksAfterEachTest`, I understand it may be due to trying to come up with a simple example, but I think is worth mentioning it just in case :)

**Comment by stevebakh** [comment]
Ah, that wasn't immediately clear, thanks for clarifying.

For reference, yes, the sample code was just meant to demonstrate the compilation failure, but my actual tests were making use of the `ResetMocksAfterEachTest` trait's functionality.

Without having investigated further just yet, using `org.mockito.IdiomaticMockito` breaks my tests (seems the wildcard `*` for `any` doesn't exist here). My initial workaround was simply to reset the mocks after each test.

**Comment by ultrasecreth** [comment]
That's because the scalatest version if `IdiomaticMockito` already mixes in `ArgumentMatchersSugar` for you, the one in the core library doesn't so you have to manually add `with ArgumentMatchersSugar` to get access to `*` and all the other argument matchers.

**Comment by stevebakh** [comment]
Ok, thanks again, appreciate you taking the time to answer.
