### ISSUE TITLE
Feature request: no nulls by default.

### ISSUE THREAD

**Issue by aselamal** [mockito/mockito-scala#27]
In scala code `null` is  rarely used in favour instead of `Option.None` or for collections an empty collection. As a result the actual code is not checking or expecting null. 

This doesn't play well with mockito which returns nulls by default for non-stubbed methods, is it possible to somehow wire up something to change this behaviour inside this framework itself. 

So it could default for e.g. any `Option[T]` into `None`, `List[T]` into `Nil` , etc.

**Comment by bbonanno** [comment]
Thanks for raising this, I'm actually working on it already :)

Keep tuned

**Comment by bbonanno** [comment]
Hi @aselamal, is still work in progress (and part of a bigger refactor) but you can check the PR #30 if you like, it would be nice to have a second opinion on it

**Comment by aselamal** [comment]
@bbonanno cool, progress so quickly! 
I have a couple of points

a) For `Try` ( and I guess `Future`) would be nicer if it could default to its "pure" function so for e.g. `Try[Option[String]]` becomes `scala.util.Success(None)`, does type erasure make this impossible?

b) Is there some way this could be extensible so the users could hook in other types? Thinking especially of classes introduced by libraries like cats.

**Comment by bbonanno** [comment]
@krever @aselamal @tpalanga I'm thinking in making empty values something not enabled by default, the reason being that with the smart-nulls, you would still get a "List" or an "Option" but as soon as your code tries to call something on them they'll fail and tell the user he's trying to use the result of something he didn't stub

I think this will help finding a lot of false positives/negatives, for example

```scala
class UserRepository {
  def find(id: Int): Option[User]
}
class UserController(userRepository: UserRepository) {
  def get(userId: Int): Option[Json] = userRepository.find(userId).map(_.toJson)
}

class UserControllerTest extends WordSpec with IdiomaticMockito {

  "get" should {
     "return the expected json" in {
        val repo = mock[UserRepository]
        val testObj = new UserController(repo)

        testObj.get(123) shouldBe Some(Json(....)) //overly simplified for clarity
      }
    }
}
```

Now, in that example that test will fail in 3 different ways

1) With the standard implementation of Mockito, the mock would return null and we would get a NullPointerException, which we all agree it's far from ideal, as it's hard to know where did it happen
2) With the default/empty values, we would get a `None`, so the final result would be `None` and we will get an assertion error as `None` is `Some(Json(....))`, but I'm not sure how much improvement over the NPE this would be, because in a non-trivial method we may have many dependencies returning `Option` and it could be hard to track which one is returning `None` and why
3) With a smart-null, we would return a `mock[Option]` and as soon as our code calls to `.map()` that mock would fail with an exception telling you what non-stubbed method was called and on which mock (in the example would say something you called the find method on some mock of type UserRepository) , check [here](https://github.com/mockito/mockito-scala/pull/30/files#diff-d4e63d35660d8605987ba10653a5a7c8R43) for more details.

What do you think? shouldn't the 3rd option be the only thing we need for anything that is not a primitive?

**Comment by Krever** [comment]
Smart nulls are the best option for me, definitely.

I would put empty valies somewhere in the lib, as you have already written it, but not as a default for sure.

**Comment by aselamal** [comment]
To me its like the the `RETURN_DEEP_STUBS` option, so perhaps not on by default but something you can turn on easily for a given mock because I agree it depends on use case.

```
    val a = external.getConfig().getOrElse("my-default")
```

without a None return this would fail and force me to mock.

However a "Java" style solution with null guards would have handled it.
```
var a = external.getConfig()
if(a == null)  a = "my-default"
```

**Comment by bbonanno** [comment]
That's exactly what we have now, check this test
https://github.com/mockito/mockito-scala/pull/30/files#diff-757050a165ef4dd5d1090f1e22959dc9R128

**Comment by bbonanno** [comment]
PR #30 solves this, empty values are not enabled by default but we don't return nulls when possible
Empty values for Scala are available by using the `ReturnsEmptyValues` as the mock default answer
