### ISSUE TITLE
Enable releases to Maven Central via Bintray

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito-scala#320]
Enable releases to Maven Central via Bintray

**Comment by ultrasecreth** [comment]
@mockitoguy I think I did all the required changes, but the release step is failing, would you mind having a look? I think the repo is missing some credentials https://github.com/mockito/mockito-scala/runs/1602326603?check_suite_focus=true

**Comment by mockitoguy** [comment]
@bbonanno, I just added "BINTRAY_API_KEY" secret to the repository

**Comment by mockitoguy** [comment]
Also added NEXUS_TOKEN_USER, NEXUS_TOKEN_PWD secrets for maven central releases

**Comment by ultrasecreth** [comment]
@mockitoguy the PR you merged failed to release :( 
It seems it's something related to shipkit, but not sure what, as it seems to be executing the same command that travis was using to release

**Comment by mockitoguy** [comment]
Looking...

**Comment by mockitoguy** [comment]
@bbonanno, I should be able to fix the releases soon. Can you help me with something related to SBT? How can we avoid running tests when invoking the build? Currently, the "release" CI step performs the tests *again*, see in #338, I needed to add `build` step before `bintrayUpload`. Thanks!

**Comment by ultrasecreth** [comment]
@mockitoguy I think what you want is `+package` rather than `build`
Notice the `+` sign, which is important as it tells SBT to package the lib for all the supported versions of Scala.

You'll see that for every module, 3 JARs are generated, for instance, the `core` module generates

- `core/target/scala-2.11/mockito-scala_2.11-<version>.jar`
- `core/target/scala-2.12/mockito-scala_2.13-<version>.jar`
- `core/target/scala-2.13/mockito-scala_2.13-<version>.jar`

Somehow shipkit was dealing with these just fine, I mention it just in case something has been changed in how it picks the artifacts to be deployed.

**Comment by mockitoguy** [comment]
Actually, I'll create a new ticket.
