### ISSUE TITLE
Feature request: unify matchers and raw values

### ISSUE THREAD

**Issue by Krever** [mockito/mockito-scala#34]
This was discussed in core mockito here: https://github.com/mockito/mockito/issues/1398 but it doesnt seem to be available soon. 

Considering that with mockito-scala we don't have to care about compatibility maybe we can somehow implement this feature here? 

Its so annoying I would even consider spending some time on implementing this during the weekend but I don't have a good idea on how to achieve this. Any help/ideas would be welcome.

**Comment by bbonanno** [comment]
@Krever I think this needs a change in the API, I added it as part of the goals for version 1.x.x, please take a look in #37 
Also given that issue is a big rehaul of the whole thing I'd like as much input (and contributions if possible) as possible :)

I'm closing this one as I don't think this can be achieved with the current API
