### ISSUE TITLE
Mocks do not work with scala parallel collections

### ISSUE THREAD

**Issue by dkulichkin** [mockito/mockito-scala#390]
Please see the example below:

```
import org.mockito.ArgumentMatchers.any
import org.mockito.IdiomaticMockito.StubbingOps
import org.mockito.MockitoSugar
import org.scalatest.{FlatSpec, Matchers}

class DemoTestSpec extends FlatSpec with Matchers with MockitoSugar {
  import MyService._

  def methodToTest(): Int = {
    val res = for {
      str <- List("foo", "bar", "baz").par  // the test works if .par is removed
    } yield getLength(str)
    res.sum
  }

  "MyService" should "work correctly" in {
    // checking if non-mocked works
    methodToTest() shouldBe 9

    withObjectMocked[MyService.type] {
      MyService.getLength(any()) returns 10
      methodToTest() shouldBe 30  // crashes invoking the real method in fact
    }
  }

}

object MyService {
  def getLength(x: String) = {
    println("real getLength")
    x.length
  }
}
```

**Comment by ultrasecreth** [comment]
hi @dkulichkin , I just refreshed my mind with the code.
Unfortunately, the feature of mocking a Scala `object` (as opposed to a class instance) only works on single threaded code, this is because a `static` field has to be overriden and if it was overriden globally it wouldn't work with parallel tests, so it's done on a thread-local basis.

changing the test to be like 
```class Issue390 extends AnyFlatSpec with Matchers with MockitoSugar {
  val service = mock[MyService]

  def methodToTest(): Int = {
    import service._
    val res = for {
      str <- List("foo", "bar", "baz").par // the test works if .par is removed
    } yield getLength(str)
    res.sum
  }

  "MyService" should "work correctly" in {
    when(service.getLength(any())) thenReturn 10

    methodToTest() shouldBe 30 // crashes invoking the real method in fact
  }

}

class MyService {
  def getLength(x: String) = {
    println("real getLength")
    x.length
  }
}
```
makes the test pass, although I'm not sure if that works for your codebase

If not, let me know more about your exact req so we can see if there is any workaround

**Comment by dkulichkin** [comment]
Thanks @bbonanno I guess we can adopt our service (a repository in this case) to become a class, even though services are usually singletons by nature.

**Comment by ultrasecreth** [comment]
You can make your `object` implements a `trait` where the behaviour is, like `trait` + `companion object` and then inject the trait as default params (or constructor injection). This way you have the best of both worlds, a singleton in prod that it is easily replaceable for test purposes :)
