### ISSUE TITLE
Not able to use mock[] with type constructors

### ISSUE THREAD

**Issue by Krever** [mockito/mockito-scala#71]
I tried to use `IdiomaticMockitoFixture` with `monix.eval.Task` which resulted in ClassCastException

Here is a minimized example:
File1.scala:
```scala
import org.mockito.IdiomaticMockito

object File1 extends IdiomaticMockito {

  trait Algebra[T] {
    def operation: T
  }

  class Foo

  //We cannot mock type constructors directly
  trait TestAlgebra extends Algebra[Foo]

  def main(args: Array[String]): Unit = {
    val m = mock[TestAlgebra]
    m.operation.shouldReturn(new Foo)
    ()
  }

}
```
Result:
```
Exception in thread "main" java.lang.ClassCastException: org.mockito.codegen.Object$MockitoMock$1394191462 cannot be cast to File1$Foo
	at File1$TestAlgebra$MockitoMock$1095682068.operation(Unknown Source)
	at File1$TestAlgebra$MockitoMock$1095682068.operation(Unknown Source)
	at File1$.main(File1.scala:16)
	at File1.main(File1.scala)

```

If I make `Algebra` not parametrized or use `Mockito.mock`.  My blind guess is that it has something to do with proxies used for smart null pointers.

**Comment by ultrasecreth** [comment]
Ok, I can see the problem, what I don't understand is that if you can't do `mock[Algebra[Baz]]` because it doesn't work or because you want to use an existent type that already extends `Algebra[T]`

For the problem itself, it seems that the reflection API doesn't provide out of the box generic return types, I'm looking for a way to fix it (but I don't have high hopes)

In the meantime, to solve your problem you have 2 options

a) Follow the good practice of not mocking what you don't own :)
b) Create the mock like `val m = mock[TestAlgebra](DefaultAnswers.ReturnsDefaults)` (You guessed it right, the problem is with the smart nulls, so this would re-instate the java behaviour for which the mock returns `null` without trying to be smart about it)

Please let me know how it goes

**Comment by Krever** [comment]
I create proxy trait `TestAlgebra` because mocking `Algebra[Baz]` directly doesn't work. If I remember correctly that's because there is no TypeTag available.

Thanks for the solutions! I don't fully understand a) (but I would love to!) but b) sounds good, wish I could come up with this myself.

**Comment by ultrasecreth** [comment]
@Krever I tried `mock[Algebra[Baz]]` and it works without any problem, I can only observe the `ClassCastException` when I use the `TestAlgebra`

Is the type you're trying to mock a Monix one or it's part of your app?

**Comment by Krever** [comment]
I believe I had this problem with Monix one. I can reproduce this tomorrow. The only difference I can recall now is that originally my algebra looked like this:
```
trait Algebra[F[_]] {
  def x: F[Unit]
}
```

So it was parametrized by the type constructor, not type itself. If this works as well I will try that tomorrow and let you know what was the exact problem.
