### ISSUE TITLE
Publish stable version for mockito-scala-scalatest to maven central

### ISSUE THREAD

**Issue by xysun** [mockito/mockito-scala#98]
Currently in maven central there's only 1.4.0 beta versions ([link](https://search.maven.org/search?q=g:org.mockito%20AND%20a:mockito-scala-scalatest_2.12&core=gav)). Any chance to publish a stable version there? 

Thanks.

**Comment by ultrasecreth** [comment]
@xysun The problem is that I need to keep the versions in-line and the specs2 module is a proper beta, core and scalatest are not, but can't have different versions sadly (due to the release tool we use and stuff). 
Feel free to treat them as final and use them for the time being, I'll try to get feedback on the specs2 module and publish the final versions of everything as soon as I can

**Comment by ultrasecreth** [comment]
v 1.4.1 published!
